pipeline {
    agent {
        node {
            label 'social-build'
            customWorkspace "c:\\jenkins\\ci_buid_${env.BUILD_NUMBER}"
            
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Executing build...'
                dir ("${env.WORKSPACE}") {
                    powershell "${env.WORKSPACE}/BuildTeamCity/tl_buildCode.ps1 -CleanBuild -ConfigurationToBuild Debug"
                }
            }
        }
        stage('Unit tests') {
            steps {
                echo 'Run unit tests...'
                dir ("${env.WORKSPACE}") {
                    powershell "${env.WORKSPACE}/BuildJenkins/CiBuild/vstest.ps1" 
                }
                
                echo 'Preparing coverage report...'
                dir ("${env.WORKSPACE}") {
                    powershell "${env.WORKSPACE}/BuildJenkins/calcCoverage.ps1" 
                }
                
                echo 'Publishing coverate report...'
                publishHTML (target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'coverageReports',
                    reportsFiles: 'index.html',
                    reportName: 'Coverage'
                ])
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'output/binaries/**,output/*.wsp,Artifacts/*.zip', allowEmptyArchive: true
        }
    }
}